---
name: Docker Image Ansible
on:
  workflow_run:
    workflows: [ "Docker Image Default" ]
    branches: [ main ]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_base_images: ["alpine:3.14", "debian:bullseye-slim"]
        latest_tag: ["false"]
        include:
          - docker_base_images: "alpine:latest"
            latest_tag: "true"
    steps:
      - uses: actions/checkout@v1
      - run: bash ./scripts/build.sh
        env:
          FLAVOR: "ansible"
          FROM_IMAGE: "rewardenv/docker-toolbox"
          IMAGE_NAME: "docker-toolbox-ansible"
          DOCKER_BASE_IMAGE: ${{ matrix.docker_base_images }}
          LATEST_TAG: ${{ matrix.latest_tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PUSH: "true"
          DOCKER_BUILD_PLATFORM: "linux/amd64,linux/arm/v7,linux/arm64"
