---
name: Docker Image Ansible
on:
  workflow_run:
    workflows: [ "Docker Image Default" ]
    branches: [ main ]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_base_images: [ "alpine:3.20", "debian:bullseye-slim", "debian:bookworm-slim", "ubuntu:jammy" ]
        latest_tag: ["false"]
        include:
          - docker_base_images: "alpine:latest"
            latest_tag: "true"
    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: mirror.gcr.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - run: bash ./scripts/build.sh
        env:
          FLAVOR: "ansible"
          FROM_IMAGE: "rewardenv/docker-toolbox"
          IMAGE_NAME: "docker-toolbox-ansible"
          DOCKER_BASE_IMAGE: ${{ matrix.docker_base_images }}
          LATEST_TAG: ${{ matrix.latest_tag }}
          PUSH: "true"
          DOCKER_USE_BUILDX: "true"
          DOCKER_BUILD_PLATFORM: "linux/amd64,linux/arm64"
