---
name: Docker Image Default
on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_base_images: ["alpine:3.20", "debian:bullseye-slim", "debian:bookworm-slim", "ubuntu:jammy"]
        latest_tag: ["false"]
        include:
          - docker_base_images: "alpine:latest"
            latest_tag: "true"
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - run: bash ./scripts/build.sh
        env:
          FLAVOR: "default"
          DOCKER_BASE_IMAGE: ${{ matrix.docker_base_images }}
          LATEST_TAG: ${{ matrix.latest_tag }}
          PUSH: "true"
          DOCKER_USE_BUILDX: "true"
          DOCKER_BUILD_PLATFORM: "linux/amd64,linux/arm64"
